
#NODE_CLASS_MAPPINGS = {
#    "AnyAspectRatio": AnyAspectRatio
#}

from .AnyAspectRatio import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
